### ISSUE TITLE
Can not run evaluation on V100 GPU

### ISSUE THREAD

**Issue by zhengsipeng** [facebookresearch/r3m#17] opened 2022-06-15 15:53 UTC
Thank you for your great work,
However, I have some problems when running your evaluation code.
My GPU enviroment is Tesla V100-32 GPU, and it always reports such rendering error: 
```
Found 0 GPUs for rendering. Using device 0.
File "mjsim.pyx", line 156, in mujoco_py.cymj.MjSim.render
  File "mjsim.pyx", line 158, in mujoco_py.cymj.MjSim.render
  File "mjrendercontext.pyx", line 46, in mujoco_py.cymj.MjRenderContext.__init__
  File "mjrendercontext.pyx", line 114, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "opengl_context.pyx", line 130, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
RuntimeError: Failed to initialize OpenGL
```
The bug happens here in L184-L191 of obs_wrappers.py
```
def get_image(self):
        if self.camera_name == "default":
            img = self.sim.render(width=self.width, height=self.height, depth=self.depth,
                            device_id=self.device_id)
        else:
            img = self.sim.render(width=self.width, height=self.height, depth=self.depth,
                              camera_name=self.camera_name, device_id=self.device_id)
        img = img[::-1,:,:]
        return img
```
So I wonder what GPU enviroment do you use in your evaluation experiments? Is it the problem of GPU type or the problem of my installation mistake?

**Comment by aravindr93** [comment] 2022-06-15 16:08
Thanks for your interest.

I believe we use V100 for our experiments, so the issue is unlikely to be the GPU type.

This might be more related to compilation of mujoco-py and headless rendering. Can you refer to install instructions and pointers in this page and try again? https://github.com/aravindr93/mjrl/tree/master/setup

**Comment by zhengsipeng** [comment] 2022-06-15 16:12
> Thanks for your interest.
> 
> I believe we use V100 for our experiments, so the issue is unlikely to be the GPU type.
> 
> This might be more related to compilation of mujoco-py and headless rendering. Can you refer to install instructions and pointers in this page and try again? https://github.com/aravindr93/mjrl/tree/master/setup



> Thanks for your interest.
> 
> I believe we use V100 for our experiments, so the issue is unlikely to be the GPU type.
> 
> This might be more related to compilation of mujoco-py and headless rendering. Can you refer to install instructions and pointers in this page and try again? https://github.com/aravindr93/mjrl/tree/master/setup

Thank you for your reply, I will try it again,
Just make sure: do you render your observation images under headless server as well?

**Comment by suraj-nair-1** [comment] 2022-06-15 16:20
Yes, we use headless rendering. I'd recommend first verifying that you can headless render images from any standard mujoco env (e.g. hopper). If that works, rendering for the R3M eval should work as well.

**Comment by suraj-nair-1** [comment] 2022-06-16 02:26
Closing this for now as this is not an r3m issue, but rather a mujoco-py rendering issue.

**Closed by suraj-nair-1** 2022-06-16 02:26 UTC
